const CART_ACTION = {
    ADD_TO_CART: 'ADD_TO_CART',
    ADD_ITEM_QUANTITY: 'ADD_ITEM_QUANTITY',
    REMOVE_ITEM_QUANTITY: 'REMOVE_ITEM_QUANTITY',
    CLEAR_ITEM: 'CLEAR_ITEM'
}

export default CART_ACTION