const PRODUCTS_ACTION = {
    FETCH_PRODUCTS_START : 'FETCH_PRODUCTS_START',
    FETCH_PRODUCTS_SUCCESS : 'FETCH_PRODUCTS_SUCCESS',
    FETCH_PRODUCTS_FAILURE : 'FETCH_PRODUCTS_FAILURE',
}

const SELECTED_PRODUCT_ACTION = {
    FETCH_PRODUCT_START : 'FETCH_PRODUCT_START',
    FETCH_PRODUCT_SUCCESS : 'FETCH_PRODUCT_SUCCESS',
    FETCH_PRODUCT_FAILURE : 'FETCH_PRODUCT_FAILURE',
}

export {PRODUCTS_ACTION, SELECTED_PRODUCT_ACTION};
